### PR TITLE
Lumical_o1_v01: change det type flags for purely passive use of this detector

### LINKED ISSUE #495: LumiCal DetType flags are set for non-sensitive parts as well
### Check duplicate issues.

- [ ] Checked for duplicates

### Goal

# Issue in `FCCee/CLD/compact/CLD_o2_v07/LumiCal_o3_v02_05.xml`:
The `LumiCal`, along with `LumiCalInstrumentation`, `LumiCalCooling`, and `LumiCalBackShield`, all use a driver/type that sets the `DetType` flags (`CALORIMETER`, `ENDCAP`, `ELECTROMAGNETIC`, `FORWARD`). This leads to ambiguity when calling `getExtension` with these four flags, causing the following error when executing `k4run` as follows in `ILDConfig`:
```
export CIF1="--compactFile $K4GEO/FCCee/ILD_FCCee/compact/ILD_FCCee_v01/ILD_FCCee_v01.xml"

ddsim \
--inputFiles Examples/bbudsc_3evt/bbudsc_3evt.stdhep \
--outputFile data/test_if1_SIM.edm4hep.root \
$CIF1 \
--steeringFile ddsim_steer.py

k4run ILDReconstruction.py \
$CIF1 \
--outputFileBase data/testFCC1_if1 \
--inputFiles data/test_if1_SIM.edm4hep.root \
--lcioOutput off
```
Error:
```
[ ERROR "MyDDMarlinPandora"] Marlin pandora failed to process event: std exception  getExtension: selection is not unique (or empty)  includeFlag: DetType( 0x82a) : CALORIMETER,       ENDCAP, FORWARD, ELECTROMAGNETIC,  excludeFlag: DetType( 0x20000) : AUXILIARY,  --- found detectors : LumiCal, LumiCalBackShield, LumiCalCooling, LumiCalInstrumentation,             1 MyDDMarlinPandora   FATAL Standard std::exception is caught in sysExecute
MyDDMarlinPandora   ERROR std::exception
k4FWCore__Algs      FATAL Standard std::exception is caught in sysExecute
k4FWCore__Algs      ERROR std::exception
k4FWCore__Seque...  FATAL Standard std::exception is caught in sysExecute
k4FWCore__Seque...  ERROR std::exception
EventLoopMgr        FATAL .executeEvent(): Standard std::exception thrown by k4FWCore__Sequencer
EventLoopMgr        ERROR std::exception
EventLoopMgr      WARNING Execution of algorithm k4FWCore__Sequencer failed
EventLoopMgr        ERROR Error processing event loop.
EventLoopMgr        ERROR Terminating event processing loop due to errors
EventLoopMgr        ERROR Terminating event processing loop due to errors
```

For ILD, a hotfix is available [here](https://github.com/Victor-Schwan/k4geo/tree/fullFCCreco), which introduces an additional passive `LumiCal_01_v01_passive` driver. This driver does not set the flags and is used for non-sensitive parts, resolving the issue.

### Operating System and Version

Ubuntu 24.04.2 LTS

### compiler

gcc13

### The version of the key4hep stack

nightlies from 2025-07-18

### Package Version

k4geo: 4d9ae7c5b5d3ef58c007e3ee21e3171c34fa97ec

### Reproducer

see above, execute in `ILCSoft/ILDConfig` on `master`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andresailer**
To ease the review process, please consider the following before opening a pull request:
- [x] the code is sufficiently well documented (e.g. inline comments)
- [x] the relevant README(s) were updated. See e.g. https://github.com/key4hep/k4geo/blob/main/detector/calorimeter/README.md or https://github.com/key4hep/k4geo/blob/main/FCCee/IDEA/compact/README.md
- [x] the code is covered by tests. See https://github.com/key4hep/k4geo/blob/main/test/CMakeLists.txt
- [x] the PR source branch has been rebased (`--ff-only`) to `k4geo/main`
- [x] the PR does not contain any additions or modifications that do not belong to it
- [x] The release notes below contain a succinct and comprehensive description of the changes that are sufficiently self-explanatory

BEGINRELEASENOTES
- Lumical_o1_v01: only set calorimeter type flags for detectors with sensitive elements, otherwise use SUPPORT and AUXILIARY. Fixes #495 

ENDRELEASENOTES

### CODE REVIEW

File: detector/fcal/LumiCal_o1_v01_geo.cpp [hunk 1]
```diff
@@ -56,6 +44,10 @@ static Ref_t create_detector(Detector& theDetector, xml_h element, SensitiveDete
   xml_det_t xmlLumiCal = element;
   const std::string detName = xmlLumiCal.nameStr();
 
+  // only set detector like type flags if there is a sensitive element in this detector, needed to unambniguously
+  // identify the actual lumical in e.g., Pandora
+  bool have_sensitive = false;
```
Comment (tmadlener) [inline detector/fcal/LumiCal_o1_v01_geo.cpp:49]:
```suggestion
  bool haveSensitive = false;
```
Up to you to decide as we are a bit all over the place (already just in this file) with the spelling of variables. Usually we go with camelCase (and that also seems to be the majority here).

Comment (andresailer) [reply detector/fcal/LumiCal_o1_v01_geo.cpp]: True! I changed to camelCase!

**Comment by tmadlener** [comment]
@Victor-Schwan is it easily possible for you to verify that these changes indeed fix #495?

Purely from the code they look sensible, but it would be nice to have confirmation.

**Comment by tmadlener** [comment]
:grimacing: it doesn't do that for me.

**Comment by tmadlener** [comment]
new experience:
image

old experience: (There is a `switch back` button on the top right corner next to preview)
image
